### ISSUE TITLE
http://127.0.0.1:8090 failed

### ISSUE THREAD

**Issue by BroadDong** [facebook/Surround360#106] opened 2016-09-18 12:10 UTC
Now I run into a problem as shown below.Could you tell me how I should solve?
![2016-09-19 19_52_48____________](https://cloud.githubusercontent.com/assets/20699811/18615539/d0f5ffb6-7ddb-11e6-8456-b0ceaf28c269.png)

**Comment by dangsiper** [comment] 2016-09-19 06:38
Hi @BroadDong 
Would you please leave your email, then we can exchange our info more convenient.

**Comment by BroadDong** [comment] 2016-09-19 07:10
@dangsiper ，1418592293@qq.com

**Comment by dangsiper** [comment] 2016-09-19 07:22
Hi @BroadDong 
This problem may be caused by you haven't ran ffserver.
You should first run:
<code>
ffserver -f configs/ffserver.conf&
</code>
, then run the CameraControl program.

**Comment by aparrapo** [comment] 2017-02-19 02:01
@BroadDong did @dangsiper 's suggestion fix your issue?

**Comment by aparrapo** [comment] 2017-04-22 19:45
This version of the camera capture is no longer on the repo. Closing this issue :)

**Closed by aparrapo** 2017-04-22 19:45 UTC
